name: "Meteociel Screenshot"
version: "2.0.3"
slug: "meteociel_screenshot"
description: "Capture périodique du graphique vent de meteociel (Le Dramont)"
arch:
  - amd64
init: false
map:
  - config:rw
